[[#meta]]
aheui-path: $HOME/aheui
os: ubuntu-20.04
snippets-repo: aheui/snippets
snippets-ref: ce34b1443a1c70b0cac1d8ed6304a65fee485082
if-cache-miss: steps.cache.outputs.cache-hit != 'true'

steps-cache: |
  - name: Set AHEUI_PATH
    run: |
      echo "::set-env name=AHEUI_PATH::[[aheui-path]]"
      mkdir -p "[[aheui-path]]"

  - id: cache
    uses: actions/cache@v2
    with:
      path: ${{ env.AHEUI_PATH }}
      key: aheui-path-v5-[[repo]]-[[ref]]-[[os]]-[[revision]]
[[/meta]]

name: compile-rev2
on:
  push:
    branches:
    - actions
    paths:
    - .github/workflows/benchmark.yaml

jobs:
  [[#files]]
  compile__[[name]]:
    runs-on: [[os]]

    steps:
    [[> steps-cache]]
    - run: mkdir -p "$AHEUI_PATH"
    - uses: actions/checkout@v2
      with:
        repository: [[repo]]
        ref: [[ref]]
    [[#steps]]
    - [[#render]][[.]][[/render]]
    [[/steps]]

  test__[[name]]:
    runs-on: [[os]]
    needs:
    - compile__[[name]]

    steps:
    [[> steps-cache]]
    - run: false
      if: [[if-cache-miss]]
    - name: Getting aheui test cases
      uses: actions/checkout@v2
      with:
        repository: [[snippets-repo]]
        ref: [[snippets-ref]]

    - run: AHEUI=$AHEUI_PATH/run-aheui bash test.sh standard

  [[/files]]

  result:
    runs-on: [[os]]
    needs:
    [[#files]]
    - test__[[name]]
    [[/files]]
    steps:
    - run: 'true'
