{
  "name": "compile-rev2",
  "on": {
    "push": {
      "branches": [
        "actions"
      ],
      "paths": [
        ".github/workflows/benchmark.yaml"
      ]
    }
  },
  "jobs": {
    "xnuk-haskell-aheui": {
      "needs": [],
      "env": {
        "REPO": "xnuk/haskell-aheui",
        "REF": "bf471483ae137e91f4eaf71ec32bb07e36c83df9"
      },
      "runs-on": "ubuntu-20.04",
      "steps": [
        {
          "run": "echo \"::set-env name=AHEUI_PATH::$HOME/aheui\""
        },
        {
          "id": "cache",
          "uses": "actions/cache@v2",
          "with": {
            "path": "${{ env.AHEUI_PATH }}",
            "key": "aheui-path-v1-${{ env.REPO }}-${{ env.REF }}-${{ runner.os }}-v1"
          }
        },
        {
          "uses": "actions/checkout@v2",
          "with": {
            "repository": "${{ env.REPO }}",
            "ref": "${{ env.REF }}"
          },
          "if": "steps.cache.outputs.cache-hit != 'true'"
        },
        {
          "uses": "actions/setup-haskell@v1.1",
          "if": "steps.cache.outputs.cache-hit != 'true'"
        },
        {
          "run": "ghc -O2 main.hs -o \"$AHEUI_PATH\"/run-aheui",
          "if": "steps.cache.outputs.cache-hit != 'true'"
        }
      ]
    },
    "test__xnuk-haskell-aheui": {
      "needs": [
        "xnuk-haskell-aheui"
      ],
      "env": {
        "REPO": "xnuk/haskell-aheui",
        "REF": "bf471483ae137e91f4eaf71ec32bb07e36c83df9"
      },
      "runs-on": "ubuntu-20.04",
      "steps": [
        {
          "run": "echo \"::set-env name=AHEUI_PATH::$HOME/aheui\""
        },
        {
          "id": "cache",
          "uses": "actions/cache@v2",
          "with": {
            "path": "${{ env.AHEUI_PATH }}",
            "key": "aheui-path-v1-${{ env.REPO }}-${{ env.REF }}-${{ runner.os }}-v1"
          }
        },
        {
          "name": "Is binary given?",
          "run": "false",
          "if": "steps.cache.outputs.cache-hit != 'true'"
        },
        {
          "uses": "actions/checkout@v2",
          "with": {
            "repository": "aheui/snippets",
            "ref": "ce34b1443a1c70b0cac1d8ed6304a65fee485082"
          }
        },
        {
          "run": "AHEUI=\"$AHEUI_PATH/run-aheui\" bash test.sh standard"
        }
      ]
    }
  }
}
