
name: compile-rev2
on:
  push:
    branches:
    - actions
    paths:
    - .github/workflows/benchmark.yaml

jobs:
  compile__Algy--aheui-cc:
    runs-on: ubuntu-20.04

    steps:
    - name: Set AHEUI_PATH
      run: |
        echo "AHEUI_PATH=$HOME/aheui" >> $GITHUB_ENV
        mkdir -p "$HOME/aheui"

    - id: cache
      uses: actions/cache@v2
      with:
        path: ${{ env.AHEUI_PATH }}
        key: aheui-path-v6-Algy/aheui-cc-d6bdabd3a95c80e4b506badf674304a3c79cd4b1-ubuntu-20.04-beta-1
    - uses: actions/checkout@v2
      if: steps.cache.outputs.cache-hit != 'true'
      with:
        repository: Algy/aheui-cc
        ref: d6bdabd3a95c80e4b506badf674304a3c79cd4b1
    - {"uses":"actions/setup-python@v2","with":{"python-version":"pypy2"},"if":"steps.cache.outputs.cache-hit != 'true'"}
    - {"run":"rm -rf .git/\ncat <<EOF > run-aheui\n#!/bin/sh\npypy ahcc.py -o runner $@ && ./runner\nEOF\nchmod +x run-aheui\ncp -R . \"$AHEUI_PATH\"\n","if":"steps.cache.outputs.cache-hit != 'true'"}

  test__Algy--aheui-cc:
    runs-on: ubuntu-20.04
    needs:
    - compile__Algy--aheui-cc

    steps:
    - name: Set AHEUI_PATH
      run: |
        echo "AHEUI_PATH=$HOME/aheui" >> $GITHUB_ENV
        mkdir -p "$HOME/aheui"

    - id: cache
      uses: actions/cache@v2
      with:
        path: ${{ env.AHEUI_PATH }}
        key: aheui-path-v6-Algy/aheui-cc-d6bdabd3a95c80e4b506badf674304a3c79cd4b1-ubuntu-20.04-beta-1
    - run: false
      if: steps.cache.outputs.cache-hit != 'true'
    - {"uses":"actions/setup-python@v2","with":{"python-version":"pypy2"}}
    - name: Getting aheui test cases
      uses: actions/checkout@v2
      with:
        repository: aheui/snippets
        ref: ce34b1443a1c70b0cac1d8ed6304a65fee485082

    - run: AHEUI=$AHEUI_PATH/run-aheui bash test.sh standard

  compile__aheui--caheui:
    runs-on: ubuntu-20.04

    steps:
    - name: Set AHEUI_PATH
      run: |
        echo "AHEUI_PATH=$HOME/aheui" >> $GITHUB_ENV
        mkdir -p "$HOME/aheui"

    - id: cache
      uses: actions/cache@v2
      with:
        path: ${{ env.AHEUI_PATH }}
        key: aheui-path-v6-aheui/caheui-c53987b0955870bc49d451acb623c582d4e6124e-ubuntu-20.04-v1
    - uses: actions/checkout@v2
      if: steps.cache.outputs.cache-hit != 'true'
      with:
        repository: aheui/caheui
        ref: c53987b0955870bc49d451acb623c582d4e6124e
    - {"run":"make","if":"steps.cache.outputs.cache-hit != 'true'"}
    - {"run":"mv ./aheui \"$AHEUI_PATH/run-aheui\"","if":"steps.cache.outputs.cache-hit != 'true'"}

  test__aheui--caheui:
    runs-on: ubuntu-20.04
    needs:
    - compile__aheui--caheui

    steps:
    - name: Set AHEUI_PATH
      run: |
        echo "AHEUI_PATH=$HOME/aheui" >> $GITHUB_ENV
        mkdir -p "$HOME/aheui"

    - id: cache
      uses: actions/cache@v2
      with:
        path: ${{ env.AHEUI_PATH }}
        key: aheui-path-v6-aheui/caheui-c53987b0955870bc49d451acb623c582d4e6124e-ubuntu-20.04-v1
    - run: false
      if: steps.cache.outputs.cache-hit != 'true'
    - name: Getting aheui test cases
      uses: actions/checkout@v2
      with:
        repository: aheui/snippets
        ref: ce34b1443a1c70b0cac1d8ed6304a65fee485082

    - run: AHEUI=$AHEUI_PATH/run-aheui bash test.sh standard

  compile__aheui--naheui:
    runs-on: ubuntu-20.04

    steps:
    - name: Set AHEUI_PATH
      run: |
        echo "AHEUI_PATH=$HOME/aheui" >> $GITHUB_ENV
        mkdir -p "$HOME/aheui"

    - id: cache
      uses: actions/cache@v2
      with:
        path: ${{ env.AHEUI_PATH }}
        key: aheui-path-v6-aheui/naheui-470d4f107b26dad399b3f4f9eea241240fafe69a-ubuntu-20.04-v1
    - uses: actions/checkout@v2
      if: steps.cache.outputs.cache-hit != 'true'
      with:
        repository: aheui/naheui
        ref: 470d4f107b26dad399b3f4f9eea241240fafe69a
    - {"uses":"actions/setup-node@v1","with":{"node-version":"14.x"},"if":"steps.cache.outputs.cache-hit != 'true'"}
    - {"run":"npm ci","if":"steps.cache.outputs.cache-hit != 'true'"}
    - {"run":"rm -rf .git/\nln -s cli.js run-aheui && cp -R . \"$AHEUI_PATH\"\n","if":"steps.cache.outputs.cache-hit != 'true'"}

  test__aheui--naheui:
    runs-on: ubuntu-20.04
    needs:
    - compile__aheui--naheui

    steps:
    - name: Set AHEUI_PATH
      run: |
        echo "AHEUI_PATH=$HOME/aheui" >> $GITHUB_ENV
        mkdir -p "$HOME/aheui"

    - id: cache
      uses: actions/cache@v2
      with:
        path: ${{ env.AHEUI_PATH }}
        key: aheui-path-v6-aheui/naheui-470d4f107b26dad399b3f4f9eea241240fafe69a-ubuntu-20.04-v1
    - run: false
      if: steps.cache.outputs.cache-hit != 'true'
    - {"uses":"actions/setup-node@v1","with":{"node-version":"14.x"}}
    - name: Getting aheui test cases
      uses: actions/checkout@v2
      with:
        repository: aheui/snippets
        ref: ce34b1443a1c70b0cac1d8ed6304a65fee485082

    - run: AHEUI=$AHEUI_PATH/run-aheui bash test.sh standard

  compile__xnuk--haskell-aheui:
    runs-on: ubuntu-20.04

    steps:
    - name: Set AHEUI_PATH
      run: |
        echo "AHEUI_PATH=$HOME/aheui" >> $GITHUB_ENV
        mkdir -p "$HOME/aheui"

    - id: cache
      uses: actions/cache@v2
      with:
        path: ${{ env.AHEUI_PATH }}
        key: aheui-path-v6-xnuk/haskell-aheui-bf471483ae137e91f4eaf71ec32bb07e36c83df9-ubuntu-20.04-v1
    - uses: actions/checkout@v2
      if: steps.cache.outputs.cache-hit != 'true'
      with:
        repository: xnuk/haskell-aheui
        ref: bf471483ae137e91f4eaf71ec32bb07e36c83df9
    - {"uses":"actions/setup-haskell@v1.1","if":"steps.cache.outputs.cache-hit != 'true'"}
    - {"run":"ghc -O2 main.hs -o \"$AHEUI_PATH\"/run-aheui","if":"steps.cache.outputs.cache-hit != 'true'"}

  test__xnuk--haskell-aheui:
    runs-on: ubuntu-20.04
    needs:
    - compile__xnuk--haskell-aheui

    steps:
    - name: Set AHEUI_PATH
      run: |
        echo "AHEUI_PATH=$HOME/aheui" >> $GITHUB_ENV
        mkdir -p "$HOME/aheui"

    - id: cache
      uses: actions/cache@v2
      with:
        path: ${{ env.AHEUI_PATH }}
        key: aheui-path-v6-xnuk/haskell-aheui-bf471483ae137e91f4eaf71ec32bb07e36c83df9-ubuntu-20.04-v1
    - run: false
      if: steps.cache.outputs.cache-hit != 'true'
    - name: Getting aheui test cases
      uses: actions/checkout@v2
      with:
        repository: aheui/snippets
        ref: ce34b1443a1c70b0cac1d8ed6304a65fee485082

    - run: AHEUI=$AHEUI_PATH/run-aheui bash test.sh standard

  compile__yous--raheui:
    runs-on: ubuntu-20.04

    steps:
    - name: Set AHEUI_PATH
      run: |
        echo "AHEUI_PATH=$HOME/aheui" >> $GITHUB_ENV
        mkdir -p "$HOME/aheui"

    - id: cache
      uses: actions/cache@v2
      with:
        path: ${{ env.AHEUI_PATH }}
        key: aheui-path-v6-yous/raheui-8d4afec78b69dfb52c96426a07f03201fea353b4-ubuntu-20.04-v1
    - uses: actions/checkout@v2
      if: steps.cache.outputs.cache-hit != 'true'
      with:
        repository: yous/raheui
        ref: 8d4afec78b69dfb52c96426a07f03201fea353b4
    - {"uses":"actions/setup-ruby@v1","if":"steps.cache.outputs.cache-hit != 'true'"}
    - {"run":"gem build raheui.gemspec","if":"steps.cache.outputs.cache-hit != 'true'"}
    - {"run":"rm -rf .git/\nln -s bin/raheui run-aheui && cp -R . \"$AHEUI_PATH\"\n","if":"steps.cache.outputs.cache-hit != 'true'"}

  test__yous--raheui:
    runs-on: ubuntu-20.04
    needs:
    - compile__yous--raheui

    steps:
    - name: Set AHEUI_PATH
      run: |
        echo "AHEUI_PATH=$HOME/aheui" >> $GITHUB_ENV
        mkdir -p "$HOME/aheui"

    - id: cache
      uses: actions/cache@v2
      with:
        path: ${{ env.AHEUI_PATH }}
        key: aheui-path-v6-yous/raheui-8d4afec78b69dfb52c96426a07f03201fea353b4-ubuntu-20.04-v1
    - run: false
      if: steps.cache.outputs.cache-hit != 'true'
    - {"uses":"actions/setup-ruby@v1"}
    - name: Getting aheui test cases
      uses: actions/checkout@v2
      with:
        repository: aheui/snippets
        ref: ce34b1443a1c70b0cac1d8ed6304a65fee485082

    - run: AHEUI=$AHEUI_PATH/run-aheui bash test.sh standard


  result:
    runs-on: ubuntu-20.04
    needs:
    - test__Algy--aheui-cc
    - test__aheui--caheui
    - test__aheui--naheui
    - test__xnuk--haskell-aheui
    - test__yous--raheui
    steps:
    - run: 'true'

